"""Color and shade vocabularies used for variant detection.

Terms are stored in normalized ASCII form because product titles are passed
through ``normalize_text`` before matching.  Keep Portuguese and English lists
separate for reviewability, then consume the combined set in feature code.
"""
from __future__ import annotations

PORTUGUESE_COLOR_TERMS = (
    "abobora",
    "amarelo",
    "ameixa",
    "areia",
    "azul",
    "baunilha",
    "bege",
    "bordo",
    "branco",
    "bronze",
    "canela",
    "caramelo",
    "castanho",
    "champagne",
    "chumbo",
    "ciano",
    "cinza",
    "claro",
    "cobre",
    "coral",
    "creme",
    "dourado",
    "escuro",
    "fucsia",
    "grafite",
    "laranja",
    "lilas",
    "loiro",
    "magenta",
    "marfim",
    "marrom",
    "marsala",
    "mel",
    "menta",
    "natural",
    "neon",
    "nude",
    "oliva",
    "perola",
    "pessego",
    "prata",
    "prateado",
    "preto",
    "roxo",
    "rosa",
    "rose",
    "rubi",
    "salmao",
    "terracota",
    "translucido",
    "turquesa",
    "uva",
    "verde",
    "vermelho",
    "vinho",
    "violeta",
)

ENGLISH_COLOR_TERMS = (
    "amber",
    "ash",
    "auburn",
    "beige",
    "black",
    "blond",
    "blonde",
    "blue",
    "bronze",
    "brown",
    "burgundy",
    "caramel",
    "champagne",
    "charcoal",
    "clear",
    "copper",
    "coral",
    "cream",
    "dark",
    "deep",
    "fair",
    "gold",
    "golden",
    "gray",
    "green",
    "grey",
    "honey",
    "ivory",
    "lavender",
    "light",
    "lilac",
    "medium",
    "mocha",
    "natural",
    "navy",
    "neutral",
    "nude",
    "olive",
    "orange",
    "peach",
    "pearl",
    "pink",
    "platinum",
    "purple",
    "red",
    "rose",
    "ruby",
    "salmon",
    "sand",
    "silver",
    "tan",
    "taupe",
    "terracotta",
    "translucent",
    "turquoise",
    "violet",
    "white",
    "wine",
    "yellow",
)

COLOR_VARIANT_TERMS = frozenset(PORTUGUESE_COLOR_TERMS) | frozenset(ENGLISH_COLOR_TERMS)

TRAINING_SHADE_WORDS = tuple(sorted({term.title() for term in COLOR_VARIANT_TERMS}))

